max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot
obstacle_range: 2.5
raytrace_range: 3.0

footprint: [ [0.20, 0.40], [0.20, -0.15], [-0.20, -0.15], [-0.20,0.40] ] 

inflation_radius: 3.0
update_frequency: 3.0

#width: 5.0
#height: 5.0
resolution: 0.15
map_type: costmap
observation_sources: scan point_cloud

scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true, min_obstacle_height: 0.15, max_obstacle_height: 1.0}

point_cloud: {data_type: PointCloud, topic: /filtered_cloud, marking: true, clearing: true, inf_is_valid: true}
