GlobalPlanner:
  allow_unknown: false
  default_tolerance: true
  visualize_potential: true
  # choice dijkstra (true) or a* (false)
  use_dijkstra: false
  use_quadratic: true #true
  use_grid_path: true #false

  old_navfn_behavior: false
  lethal_cost: 233 #253
  neutral_cost: 50
  cost_factor: 3.0

  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1

  #
  #planner_window_x: 0.0
  #planner_window_y: 0.0
  #publish_scale: 100.0
